POST http://127.0.0.1:8000/login/
Content-Type: application/json

{
    "username": "aldenrmd",
    "password": "@Alden123"
} 

###
POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{
    "username": "aldenrmd1",
    "password": "@Alden123",
    "email": "aldenrmd10@gmail.com"
}

###
GET http://127.0.0.1:8000/testToken/
Content-Type: application/json 
Authorization: Token ed70e65eb16ca013af6ad25a6a7f6a883b328ced

{
}

###
POST http://127.0.0.1:8000/insertPost/
Content-Type: application/json
Authorization: Token ed70e65eb16ca013af6ad25a6a7f6a883b328ced

{
    
    "username": "b;ah",
    "datePosted": "2024-04-25" ,
    "post": "blahvlah test",
    "userID": 1
}
###
POST http://127.0.0.1:8000/likePost/2/32
Content-Type: application/json
Authorization: Token ed70e65eb16ca013af6ad25a6a7f6a883b328ced

{
}


###
GET http://127.0.0.1:8000/posts/
Content-Type: application/json

{
}
###
POST http://127.0.0.1:8000/updateUserProfile/
Content-Type: application/json
Authorization: Token ed70e65eb16ca013af6ad25a6a7f6a883b328ced

{
    
    "username": "b;ah",
    "datePosted": "2024-04-25" ,
    "post": "blahvlah test",
    "userID": 1
}